-- =====================================================
-- Updated Car Upsert Functions for Comprehensive Excel Data
-- =====================================================
-- This migration updates the existing upsert functions to handle
-- the comprehensive Excel data structure with 200+ columns
-- =====================================================

-- Drop existing functions to recreate with comprehensive support
DROP FUNCTION IF EXISTS public.upsert_car_data(jsonb);
DROP FUNCTION IF EXISTS public.bulk_upsert_cars(jsonb);

-- Create the comprehensive upsert function
CREATE OR REPLACE FUNCTION public.upsert_car_data(car_data jsonb)
RETURNS TABLE(
  action TEXT,
  car_id UUID,
  brand TEXT,
  model TEXT,
  variant TEXT,
  message TEXT
) AS $$
DECLARE
  existing_car_id UUID;
  new_car_id UUID;
  car_brand TEXT;
  car_model TEXT;
  car_variant TEXT;
BEGIN
  -- Extract key fields for duplicate checking
  car_brand := car_data->>'brand';
  car_model := car_data->>'model';
  car_variant := car_data->>'variant';

  -- Check if car already exists based on brand, model, and variant
  SELECT id INTO existing_car_id
  FROM public.cars
  WHERE
    LOWER(TRIM(cars.brand)) = LOWER(TRIM(car_brand))
    AND LOWER(TRIM(cars.model)) = LOWER(TRIM(car_model))
    AND (
      (car_variant IS NULL AND cars.variant IS NULL)
      OR (LOWER(TRIM(cars.variant)) = LOWER(TRIM(car_variant)))
    )
  LIMIT 1;

  -- If car exists, skip insertion
  IF existing_car_id IS NOT NULL THEN
    RETURN QUERY SELECT
      'SKIPPED'::TEXT,
      existing_car_id,
      car_brand,
      car_model,
      car_variant,
      'Car already exists in database'::TEXT;
    RETURN;
  END IF;

  -- Insert new car with comprehensive data
  INSERT INTO public.cars (
    external_id,
    brand,
    model,
    variant,
    body_style,
    status,
    image_url,
    price,
    onroad_price_delhi,
    key_price,
    key_mileage_arai,
    key_engine,
    key_transmission,
    key_fuel_type,
    key_seating_capacity,
    engine,
    engine_type,
    top_speed,
    acceleration_0_100_kmph,
    maxpower_bhp,
    maxpower_rpm,
    maxtorque_nm,
    maxtorque_rpm,
    performance_on_alternate_fuel,
    maxengineperformance,
    maxmotorperformance,
    mileage_arai,
    powerconsumptionpermileage,
    driving_range,
    drivetrain,
    transmission,
    emissionstandard,
    turbocharger_supercharger,
    battery,
    battery_charging,
    electric_motor,
    others,
    alternatefuel,
    length_mm,
    width_mm,
    height_mm,
    wheelbase_mm,
    groundclearance_mm,
    kerbweight_kg,
    doors,
    seating_capacity,
    no_of_seating_rows,
    bootspace_liters,
    fuel_tank_capacity_liters,
    front_suspension,
    rear_suspension,
    front_brake_type,
    rear_brake_type,
    minimum_turning_radius,
    steering_type,
    wheels,
    spare_wheels,
    front_tyres,
    rear_tyres,
    four_wheel_steering,
    braking_performance,
    overspeed_warning,
    lane_departure_warning,
    emergency_brake_light_flashing,
    forward_collision_warning_fcw,
    automatic_emergency_braking_aeb,
    high_beam_assist,
    ncap_rating,
    blind_spot_detection,
    lane_departure_prevention,
    puncture_repair_kit,
    rear_cross_traffic_assist,
    airbags,
    middle_rear_three_point_seatbelt,
    middle_rear_headrest,
    tyre_pressure_monitoring_system_tpms,
    child_seat_anchor_points,
    seatbelt_warning,
    antilock_braking_system_abs,
    electronic_brakeforce_distribution_ebd,
    brake_assist_ba,
    electronic_stability_program,
    four_wheel_drive,
    hill_hold_control,
    traction_control_system_tc_tcs,
    ride_height_adjustment,
    hill_descent_control,
    limited_slip_differential_lsd,
    differential_lock,
    engine_immobilizer,
    central_locking,
    speed_sensing_doorlock,
    child_safety_lock,
    air_conditioner,
    front_ac,
    rear_ac,
    headlight_and_ignition_on_reminder,
    keyless_start_button_start,
    steering_adjustment,
    12v_power_outlets,
    cruise_control,
    parking_sensors,
    parking_assist,
    antiglare_mirrors,
    vanity_mirrors_on_sunvisors,
    heater,
    cabin_bootaccess,
    third_row_ac,
    remote_car_light_flashing_and_honking_via_app,
    geofence,
    remote_sunroof_open_close_via_app,
    over_the_air_updates_ota,
    check_vehicle_status_via_app,
    remote_car_lock_unlock_via_app,
    emergency_call,
    find_my_car,
    remote_ac_on_off_via_app,
    alexa_compatibility,
    driver_seat_adjustment,
    front_passenger_seat_adjustment,
    rear_row_seat_adjustment,
    third_row_seat_adjustment,
    seat_upholstery,
    leather_wrapped_steering_wheel,
    leather_wrapped_gear_knob,
    driver_armrest,
    rear_passenger_seats_type,
    third_row_seats_type,
    ventilated_seats,
    ventilated_seat_type,
    interiors,
    interior_colours,
    rear_armrest,
    folding_rear_seat,
    split_rear_seat,
    split_third_row_seat,
    front_seat_pocket,
    headrests,
    fourth_row_seat_adjustment,
    cup_holders,
    driver_armrest_storage,
    cooled_glove_box,
    sunglass_holder,
    third_row_cup_holders,
    one_touch_down,
    one_touch_up,
    power_windows,
    adjustable_orvm,
    turn_indicators_on_orvm,
    rear_defogger,
    rear_wiper,
    exterior_door_handles,
    rain_sensing_wipers,
    interior_door_handles,
    door_pockets,
    side_window_blinds,
    bootlid_opener,
    rear_windshield_blind,
    outside_rearview_mirrors_orvms,
    scuff_plates,
    sunroof_moonroof,
    roof_rails,
    roof_mounted_antenna,
    body_coloured_bumpers,
    chrome_finish_exhaust_pipe,
    body_kit,
    rub_strips,
    fog_lights,
    daytime_running_lights,
    headlights,
    automatic_head_lamps,
    followme_home_headlamps,
    tail_lights,
    cabin_lamps,
    headlight_height_adjuster,
    glove_box_lamp,
    lights_on_vanity_mirrors,
    rear_reading_lamp,
    cornering_headlights,
    puddle_lamps,
    ambient_interior_lighting,
    instrument_cluster,
    trip_meter,
    average_fuel_consumption,
    average_speed,
    distance_to_empty,
    clock,
    low_fuel_level_warning,
    door_ajar_warning,
    adjustable_cluster_brightness,
    gear_indicator,
    shift_indicator,
    headsupdisplay_hud,
    tachometer,
    instantaneous_consumption,
    smart_connectivity,
    integrated_indash_musicsystem,
    headunit_size,
    display,
    display_screen_for_rear_passengers,
    gps_navigation_system,
    speakers,
    usb_compatibility,
    aux_compatibility,
    bluetooth_compatibility,
    mp3_playback,
    cd_player,
    dvd_playback,
    am_fm_radio,
    ipod_compatibility,
    internal_hard_drive,
    steering_mounted_controls,
    voice_command,
    wireless_charger,
    gesture_control,
    warranty_in_years,
    warranty_in_kms,
    battery_warranty_in_years,
    battery_warranty_in_kms,
    color_name,
    color_rgb,
    ex_showroom_price,
    rto,
    insurance,
    tax_collected_at_source_tcs,
    handling_logistic_charges,
    fast_tag,
    mumbai,
    bangalore,
    delhi,
    pune,
    navi_mumbai,
    hyderabad,
    ahmedabad,
    chennai,
    kolkata,
    description,
    price_min,
    price_max,
    fuel_type,
    transmission_type,
    engine_capacity,
    mileage,
    body_type,
    images,
    specifications,
    features,
    api_source
  ) VALUES (
    car_data->>'external_id',
    car_brand,
    car_model,
    car_variant,
    car_data->>'body_style',
    COALESCE(car_data->>'status', 'active'),
    car_data->>'image_url',
    NULLIF(REGEXP_REPLACE(car_data->>'price', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'onroad_price_delhi', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'key_price', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'key_mileage_arai',
    car_data->>'key_engine',
    car_data->>'key_transmission',
    car_data->>'key_fuel_type',
    NULLIF(REGEXP_REPLACE(car_data->>'key_seating_capacity', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'engine',
    car_data->>'engine_type',
    NULLIF(REGEXP_REPLACE(car_data->>'top_speed', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'acceleration_0_100_kmph',
    NULLIF(REGEXP_REPLACE(car_data->>'maxpower_bhp', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'maxpower_rpm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'maxtorque_nm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'maxtorque_rpm', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'performance_on_alternate_fuel',
    car_data->>'maxengineperformance',
    car_data->>'maxmotorperformance',
    car_data->>'mileage_arai',
    car_data->>'powerconsumptionpermileage',
    NULLIF(REGEXP_REPLACE(car_data->>'driving_range', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'drivetrain',
    car_data->>'transmission',
    car_data->>'emissionstandard',
    car_data->>'turbocharger_supercharger',
    car_data->>'battery',
    car_data->>'battery_charging',
    car_data->>'electric_motor',
    car_data->>'others',
    car_data->>'alternatefuel',
    NULLIF(REGEXP_REPLACE(car_data->>'length_mm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'width_mm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'height_mm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'wheelbase_mm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'groundclearance_mm', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'kerbweight_kg', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'doors', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'seating_capacity', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'no_of_seating_rows', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'bootspace_liters', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'fuel_tank_capacity_liters', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'front_suspension',
    car_data->>'rear_suspension',
    car_data->>'front_brake_type',
    car_data->>'rear_brake_type',
    car_data->>'minimum_turning_radius',
    car_data->>'steering_type',
    car_data->>'wheels',
    car_data->>'spare_wheels',
    car_data->>'front_tyres',
    car_data->>'rear_tyres',
    car_data->>'four_wheel_steering',
    car_data->>'braking_performance',
    car_data->>'overspeed_warning',
    car_data->>'lane_departure_warning',
    car_data->>'emergency_brake_light_flashing',
    car_data->>'forward_collision_warning_fcw',
    car_data->>'automatic_emergency_braking_aeb',
    car_data->>'high_beam_assist',
    (car_data->>'ncap_rating')::INTEGER,
    car_data->>'blind_spot_detection',
    car_data->>'lane_departure_prevention',
    car_data->>'puncture_repair_kit',
    car_data->>'rear_cross_traffic_assist',
    (car_data->>'airbags')::INTEGER,
    car_data->>'middle_rear_three_point_seatbelt',
    car_data->>'middle_rear_headrest',
    car_data->>'tyre_pressure_monitoring_system_tpms',
    car_data->>'child_seat_anchor_points',
    car_data->>'seatbelt_warning',
    car_data->>'antilock_braking_system_abs',
    car_data->>'electronic_brakeforce_distribution_ebd',
    car_data->>'brake_assist_ba',
    car_data->>'electronic_stability_program',
    car_data->>'four_wheel_drive',
    car_data->>'hill_hold_control',
    car_data->>'traction_control_system_tc_tcs',
    car_data->>'ride_height_adjustment',
    car_data->>'hill_descent_control',
    car_data->>'limited_slip_differential_lsd',
    car_data->>'differential_lock',
    car_data->>'engine_immobilizer',
    car_data->>'central_locking',
    car_data->>'speed_sensing_doorlock',
    car_data->>'child_safety_lock',
    car_data->>'air_conditioner',
    car_data->>'front_ac',
    car_data->>'rear_ac',
    car_data->>'headlight_and_ignition_on_reminder',
    car_data->>'keyless_start_button_start',
    car_data->>'steering_adjustment',
    car_data->>'12v_power_outlets',
    car_data->>'cruise_control',
    car_data->>'parking_sensors',
    car_data->>'parking_assist',
    car_data->>'antiglare_mirrors',
    car_data->>'vanity_mirrors_on_sunvisors',
    car_data->>'heater',
    car_data->>'cabin_bootaccess',
    car_data->>'third_row_ac',
    car_data->>'remote_car_light_flashing_and_honking_via_app',
    car_data->>'geofence',
    car_data->>'remote_sunroof_open_close_via_app',
    car_data->>'over_the_air_updates_ota',
    car_data->>'check_vehicle_status_via_app',
    car_data->>'remote_car_lock_unlock_via_app',
    car_data->>'emergency_call',
    car_data->>'find_my_car',
    car_data->>'remote_ac_on_off_via_app',
    car_data->>'alexa_compatibility',
    car_data->>'driver_seat_adjustment',
    car_data->>'front_passenger_seat_adjustment',
    car_data->>'rear_row_seat_adjustment',
    car_data->>'third_row_seat_adjustment',
    car_data->>'seat_upholstery',
    car_data->>'leather_wrapped_steering_wheel',
    car_data->>'leather_wrapped_gear_knob',
    car_data->>'driver_armrest',
    car_data->>'rear_passenger_seats_type',
    car_data->>'third_row_seats_type',
    car_data->>'ventilated_seats',
    car_data->>'ventilated_seat_type',
    car_data->>'interiors',
    car_data->>'interior_colours',
    car_data->>'rear_armrest',
    car_data->>'folding_rear_seat',
    car_data->>'split_rear_seat',
    car_data->>'split_third_row_seat',
    car_data->>'front_seat_pocket',
    car_data->>'headrests',
    car_data->>'fourth_row_seat_adjustment',
    car_data->>'cup_holders',
    car_data->>'driver_armrest_storage',
    car_data->>'cooled_glove_box',
    car_data->>'sunglass_holder',
    car_data->>'third_row_cup_holders',
    car_data->>'one_touch_down',
    car_data->>'one_touch_up',
    car_data->>'power_windows',
    car_data->>'adjustable_orvm',
    car_data->>'turn_indicators_on_orvm',
    car_data->>'rear_defogger',
    car_data->>'rear_wiper',
    car_data->>'exterior_door_handles',
    car_data->>'rain_sensing_wipers',
    car_data->>'interior_door_handles',
    car_data->>'door_pockets',
    car_data->>'side_window_blinds',
    car_data->>'bootlid_opener',
    car_data->>'rear_windshield_blind',
    car_data->>'outside_rearview_mirrors_orvms',
    car_data->>'scuff_plates',
    car_data->>'sunroof_moonroof',
    car_data->>'roof_rails',
    car_data->>'roof_mounted_antenna',
    car_data->>'body_coloured_bumpers',
    car_data->>'chrome_finish_exhaust_pipe',
    car_data->>'body_kit',
    car_data->>'rub_strips',
    car_data->>'fog_lights',
    car_data->>'daytime_running_lights',
    car_data->>'headlights',
    car_data->>'automatic_head_lamps',
    car_data->>'followme_home_headlamps',
    car_data->>'tail_lights',
    car_data->>'cabin_lamps',
    car_data->>'headlight_height_adjuster',
    car_data->>'glove_box_lamp',
    car_data->>'lights_on_vanity_mirrors',
    car_data->>'rear_reading_lamp',
    car_data->>'cornering_headlights',
    car_data->>'puddle_lamps',
    car_data->>'ambient_interior_lighting',
    car_data->>'instrument_cluster',
    car_data->>'trip_meter',
    car_data->>'average_fuel_consumption',
    car_data->>'average_speed',
    car_data->>'distance_to_empty',
    car_data->>'clock',
    car_data->>'low_fuel_level_warning',
    car_data->>'door_ajar_warning',
    car_data->>'adjustable_cluster_brightness',
    car_data->>'gear_indicator',
    car_data->>'shift_indicator',
    car_data->>'headsupdisplay_hud',
    car_data->>'tachometer',
    car_data->>'instantaneous_consumption',
    car_data->>'smart_connectivity',
    car_data->>'integrated_indash_musicsystem',
    car_data->>'headunit_size',
    car_data->>'display',
    car_data->>'display_screen_for_rear_passengers',
    car_data->>'gps_navigation_system',
    (car_data->>'speakers')::INTEGER,
    car_data->>'usb_compatibility',
    car_data->>'aux_compatibility',
    car_data->>'bluetooth_compatibility',
    car_data->>'mp3_playback',
    car_data->>'cd_player',
    car_data->>'dvd_playback',
    car_data->>'am_fm_radio',
    car_data->>'ipod_compatibility',
    car_data->>'internal_hard_drive',
    car_data->>'steering_mounted_controls',
    car_data->>'voice_command',
    car_data->>'wireless_charger',
    car_data->>'gesture_control',
    NULLIF(REGEXP_REPLACE(car_data->>'warranty_in_years', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'warranty_in_kms', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'battery_warranty_in_years', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'battery_warranty_in_kms', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'color_name',
    car_data->>'color_rgb',
    NULLIF(REGEXP_REPLACE(car_data->>'ex_showroom_price', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'rto', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'insurance', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'tax_collected_at_source_tcs', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'handling_logistic_charges', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'fast_tag', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'mumbai', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'bangalore', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'delhi', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'pune', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'navi_mumbai', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'hyderabad', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'ahmedabad', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'chennai', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'kolkata', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'description',
    NULLIF(REGEXP_REPLACE(car_data->>'price_min', '[^0-9]', '', '')::INTEGER, 0),
    NULLIF(REGEXP_REPLACE(car_data->>'price_max', '[^0-9]', '', '')::INTEGER, 0),
    car_data->>'fuel_type',
    car_data->>'transmission_type',
    car_data->>'engine_capacity',
    car_data->>'mileage',
    car_data->>'body_type',
    COALESCE(car_data->'images', '[]'::jsonb),
    COALESCE(car_data->'specifications', '{}'::jsonb),
    COALESCE(car_data->'features', '[]'::jsonb),
    car_data->>'api_source'
  )
  RETURNING id INTO new_car_id;

  -- Return success
  RETURN QUERY SELECT
    'INSERTED'::TEXT,
    new_car_id,
    car_brand,
    car_model,
    car_variant,
    'Car successfully added to database'::TEXT;
END;
$$ LANGUAGE plpgsql;

-- Create the comprehensive bulk upsert function
CREATE OR REPLACE FUNCTION public.bulk_upsert_cars(cars_data jsonb)
RETURNS TABLE(
  total_processed INTEGER,
  inserted_count INTEGER,
  skipped_count INTEGER,
  error_count INTEGER,
  details jsonb
) AS $$
DECLARE
  car_record jsonb;
  result_record RECORD;
  total INTEGER := 0;
  inserted INTEGER := 0;
  skipped INTEGER := 0;
  errors INTEGER := 0;
  results jsonb := '[]'::jsonb;
BEGIN
  -- Process each car in the array
  FOR car_record IN SELECT * FROM jsonb_array_elements(cars_data)
  LOOP
    total := total + 1;

    BEGIN
      -- Try to insert/update the car
      FOR result_record IN SELECT * FROM public.upsert_car_data(car_record)
      LOOP
        -- Count the result
        IF result_record.action = 'INSERTED' THEN
          inserted := inserted + 1;
        ELSIF result_record.action = 'SKIPPED' THEN
          skipped := skipped + 1;
        END IF;

        -- Add to results array
        results := results || jsonb_build_object(
          'action', result_record.action,
          'car_id', result_record.car_id,
          'brand', result_record.brand,
          'model', result_record.model,
          'variant', result_record.variant,
          'message', result_record.message
        );
      END LOOP;

    EXCEPTION WHEN OTHERS THEN
      errors := errors + 1;
      results := results || jsonb_build_object(
        'action', 'ERROR',
        'car_id', NULL,
        'brand', car_record->>'brand',
        'model', car_record->>'model',
        'variant', car_record->>'variant',
        'message', SQLERRM
      );
    END;
  END LOOP;

  -- Return statistics
  RETURN QUERY SELECT
    total,
    inserted,
    skipped,
    errors,
    results;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- Grant permissions
-- =====================================================
GRANT EXECUTE ON FUNCTION public.upsert_car_data(jsonb) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.bulk_upsert_cars(jsonb) TO authenticated, anon, service_role;

-- =====================================================
-- Comments for documentation
-- =====================================================
COMMENT ON FUNCTION public.upsert_car_data(jsonb) IS 'Comprehensive car upsert function that handles all Excel data fields including engine, dimensions, safety, comfort, entertainment, and pricing details.';
COMMENT ON FUNCTION public.bulk_upsert_cars(jsonb) IS 'Bulk upsert function that processes multiple comprehensive car records and returns detailed statistics.';